#!/bin/bash

cp ~/.bash_aliases ~/.bashrc ~/.gitattributes ~/.gitconfig ~/.gitignore ~/.irbrc ~/.rdbgrc ~/.tmux.conf ~/.vimrc ~/.Xauthority ~/.Xdefaults ~/.Xresources /etc/xdg/xdg-xubuntu/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml ~/.bash_history ~/Documents/important-config-files 

cd ~/Documents/important-config-files

git add .
git ci -m "Updated at $(date)" --quiet
git push --quiet
